### ISSUE TITLE
DeprecationWarning: Tapable.plugin is deprecated. Use new API on `.hooks` instead

### ISSUE THREAD

**Issue by anhuiliujun** [levp/wrapper-webpack-plugin#4]
upgrade for webpack 4?

**Comment by levp** [comment]
Fixed, though unfortunately the fix now breaks backwards compatibility with older versions.
Updated the README to reflect this as well.

**Comment by WillsB3** [comment]
Hi @levp, 

I'm also seeing this issue but it appears that 2.1.0 is not yet published to npm. Is that intentional? 

Thanks
Will

**Comment by levp** [comment]
Hi @WillsB3,

This issue was solved with 2.0.0, and I checked to see that 2.1.0 was published:

![image](https://user-images.githubusercontent.com/14345625/50890170-5d574000-1402-11e9-8b70-78cdbdac0d36.png)

Not sure why you don't see it.
Do you see it as something other than 2.1.0?
What version does `npm i wrapper-webpack-plugin` install for you?

**Comment by WillsB3** [comment]
Whoops! I think I may have gotten this package confused with the similarly named `[webpack-wrapper-plugin](https://www.npmjs.com/package/webpack-wrapper-plugin)` which appears to be what we are currently using.

Sorry for the confusion 🙏🏼
